SELECT * FROM MAQUINAS;

/*MEDIA DAS MAQUINAS */

SELECT MAQUINA, AVG(QTD) AS MEDIA_QTD
FROM MAQUINAS
GROUP BY MAQUINA
ORDER BY 2 DESC;

/*ARREDONDAR */

ROUND (COLUNA,2)

SELECT MAQUINA, ROUND (AVG(QTD),2) AS MEDIA_QTD
FROM MAQUINAS
GROUP BY MAQUINA
ORDER BY 2 DESC;

/* A MODA DAS QUANTIDADES */



SELECT MAQUINA , QTD , COUNT(*) AS MODA
FROM MAQUINAS
GROUP BY MAQUINA , QTD
ORDER BY 3 DESC

/* MODA DAS QUANTIDADE DE CADA MAQUINA */

SELECT MAQUINA , QTD , COUNT(*) FROM MAQUINAS
WHERE MAQUINA = 'Maquina 01'
GROUP BY MAQUINA , QTD
ORDER BY 3 DESC
LIMIT 1;

SELECT MAQUINA , QTD , COUNT(*) FROM MAQUINAS
WHERE MAQUINA = 'Maquina 02'
GROUP BY MAQUINA , QTD
ORDER BY 3 DESC
LIMIT 1;

SELECT MAQUINA , QTD , COUNT(*) FROM MAQUINAS
WHERE MAQUINA = 'Maquina 03'
GROUP BY MAQUINA , QTD
ORDER BY 3 DESC
LIMIT 1;

/* MODA DO DATASET INTEIRO */

SELECT QTD , COUNT(*) AS MODA
FROM MAQUINAS
GROUP BY QTD
ORDER BY 2 DESC

/* MAXIMO O  MENIMO E A AMPLITUDE DAS MAQUINAS */

SELECT MAQUINA ,
ROUND(AVG(QTD),2) AS MEDIA,
MAX(QTD) AS MAXIMO,
MIN(QTD) AS MINIMO,
MAX(QTD) - MIN(QTD) AS AMPLITUDE
FROM MAQUINAS
GROUP BY MAQUINA
ORDER BY 4 DESC;


/* DESVIO PADRAO E VARIANCIA */

STDDEV_POP (COLUNA)
VAR_POP (COLUNA)

SELECT MAQUINA ,
ROUND(AVG(QTD),2) AS MEDIA,
MAX(QTD) AS MAXIMO,
MIN(QTD) AS MINIMO,
MAX(QTD) - MIN(QTD) AS AMPLITUDE,
ROUND(STDDEV_POP(QTD),2) AS DESV_PAD,
ROUND(VAR_POP(QTD),2) AS VARIANCIA
FROM MAQUINAS
GROUP BY MAQUINA
ORDER BY 4 DESC;




/* CALCULAR A MEDIANA */

CREATE OR REPLACE FUNCTION _final_median(NUMERIC[])
RETURNS NUMERIC AS
$$
SELECT AVG (val)
FROM (
SELECT val
FROM unnest ($1) val
ORDER BY 1
LIMIT 2 - MOD (array_upper ($1, 1) , 2)
OFFSET CEIL (array_upper ($1, 1) /2.0) - 1
) sub;
$$
LANGUAGE 'sql' IMMUTABLE;

CREATE AGGREGATE median (NUMERIC) (
SFUNC = array_append,
STYPE = NUMERIC [],
FINALFUNC = _final_median ,
INITCOND = '{}'
);
SELECT MEDIAN (QTD) AS MEDIANA
FROM MAQUINAS;

SELECT MEDIAN (QTD) AS MEDIANA
FROM MAQUINAS
     WHERE MAQUINA = 'Maquina 01';

	 SELECT MEDIAN (QTD) AS MEDIANA
FROM MAQUINAS
     WHERE MAQUINA = 'Maquina 02';

	 SELECT MEDIAN (QTD) AS MEDIANA
FROM MAQUINAS
     WHERE MAQUINA = 'Maquina 03';
	

INSERT INTO MAQUINAS VALUES('Maquina 01',11,15.9);
INSERT INTO MAQUINAS VALUES('Maquina 02',11,15.4);
INSERT INTO MAQUINAS VALUES('Maquina 03',11,15.7);
INSERT INTO MAQUINAS VALUES('Maquina 01',12,30);
INSERT INTO MAQUINAS VALUES('Maquina 02',12,24);
INSERT INTO MAQUINAS VALUES('Maquina 03',12,45);

INSERT INTO MAQUINAS VALUES('Maquina 01',17,25.9);
INSERT INTO MAQUINAS VALUES('Maquina 02',19,19.4);
INSERT INTO MAQUINAS VALUES('Maquina 03',16,25.7);
INSERT INTO MAQUINAS VALUES('Maquina 01',11,30);
INSERT INTO MAQUINAS VALUES('Maquina 02',5,34);
INSERT INTO MAQUINAS VALUES('Maquina 03',18,55);



SELECT MAQUINA,
COUNT(QTD) AS "QUANTIDADE",
SUM(QTD) AS "TOTAL",
ROUND (AVG(QTD),2) AS "MEDIA",
MAX(QTD) AS "MAXIMO",
MIN (QTD) AS "MINIMO",
MAX(QTD) - MIN (QTD) AS "AMPLIT.TOTAL",
ROUND (VAR_POP (QTD),2) AS "VARIANCIA",
ROUND (STDDEV_POP (QTD),2) AS "DESV.PADRAO",
ROUND (MEDIAN(QTD),2) AS "MEDIANA",
ROUND ((STDDEV_POP (QTD) / AVG (QTD)) * 100,2) AS "COEF.VARIACAO"
FROM MAQUINAS
GROUP BY MAQUINA
ORDER BY 1;


/* MODA */


SELECT * FROM MAQUINAS;

SELECT MODE() WITHIN GROUP(ORDER BY QTD) AS "MODA" FROM MAQUINAS;

SELECT MAQUINA, MODE() WITHIN GROUP(ORDER BY QTD) AS "MODA" 
FROM MAQUINAS
GROUP BY MAQUINA;

/* TODAS AS MEDIDAS */

SELECT MAQUINA,
COUNT(QTD) AS "QUANTIDADE",
SUM(QTD) AS "TOTAL",
ROUND (AVG(QTD),2) AS "MEDIA",
MAX(QTD) AS "MAXIMO",
MIN (QTD) AS "MINIMO",
MAX(QTD) - MIN (QTD) AS "AMPLIT.TOTAL",
ROUND (VAR_POP (QTD),2) AS "VARIANCIA",
ROUND (STDDEV_POP (QTD),2) AS "DESV.PADRAO",
ROUND (MEDIAN(QTD),2) AS "MEDIANA",
ROUND ((STDDEV_POP (QTD) / AVG (QTD)) * 100,2) AS "COEF.VARIACAO",
MODE() WITHIN GROUP(ORDER BY QTD) AS "MODA"
FROM MAQUINAS
GROUP BY MAQUINA
ORDER BY 1;

